language: generic 

sudo: required
services:
  - docker

before install:
  - docker build -t thomasbtatum/react-test -f ./client/Dockerfile.dev ./clent

script:
  - docker run -e CI=true thomasbtatum/react-test npm test -- --coverage

after_success:
  - docker build -t thomasbtatum/multi-client ./client
  - docker build -t thomasbtatum/multi-nginx ./nginx
  - docker build -t thomasbtatum/multi-server ./server
  - docker build -t thomasbtatum/multi-worker ./worker
