language: generic 

sudo: required
services:
  - docker

before install:
  - docker build -t thomasbtatum/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true thomasbtatum/react-test npm test -- --coverage

  #test
after_success:
  - docker build -t thomasbtatum/multi-client ./client
  - docker build -t thomasbtatum/multi-nginx ./nginx
  - docker build -t thomasbtatum/multi-server ./server
  - docker build -t thomasbtatum/multi-worker ./worker

  #Log into Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --password-stdin

  - docker push thomasbtatum/multi-client
  - docker push thomasbtatum/multi-nginx
  - docker push thomasbtatum/multi-server
  - docker push thomasbtatum/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-230323438409'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
